# Changes here will be overwritten by Copier
_commit: df1c329
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2025'
documentation: false
email: ZeliardM@gmail.com
full_name: Robert L. Morren, Jr.
github_username: ZeliardM
has_cli: false
initial_commit: false
is_django_package: false
open_source_license: Apache-2.0
open_with_editor: false
package_name: kasa_tpap_protocols
project_name: kasa-tpap-protocols
project_short_description: TPAP protocol helpers (NOC client and SPAKE2+ curve points)
project_slug: kasa-tpap-protocols
run_uv_sync: false
setup_github: false
setup_pre_commit: false

